### ISSUE TITLE
Camera Defocus/Blur

### ISSUE THREAD

**Issue by AaronWebster** [ISET/isetcam#26]
Does isetcam by itself support defocus/blur calculations, or is that strictly an iset3d feature?

**Comment by wandell** [comment]
The tutorials/optics directory has some examples of creating optical images with different amounts of defocus and other wavefront errors.  Setting the wavefront errors includes defocus, astigmatism and other parameters.  You might have a look at any of the t_wvf*.m tutorials.

Also, there are scripts with names like s_opticsDefocus*.m that may be helpful.

If these seem annoying or complex, let me know.  I have been meaning to write a simpler one just for blur.

Also, using the 'shift-invariant' optics model gives you the opportunity to specify a lens with a shift-invariant, wavelength-dependent, point spread function.  Have a look at s_opticsSI*.m

**Comment by AaronWebster** [comment]
I would really appreciated anything you have, even if an unfinished snippet.

I'm trying to verify a simple setup where the focus distance does not match the subject distance.  I took some reference images with a real camera and was able to reproduce with Blender and pbrt, but the isetcam result is suspicious.

Here's my current recipe. 

```
max_sf_cycles_per_deg = sceneGet(scene, 'max freq res', 'cpd');
sf_cycles_per_deg = linspace(0, max_sf_cycles_per_deg, ...
                             min(ceil(max_sf_cycles_per_deg), 100));

image_plane_meters = 1.0 / ((1.0 / focal_length_meters) - (1.0 / focus_distance_meters));
[D, ~] = opticsDepthDefocus(subject_distance_meters, optics, image_plane_meters);
defocus = zeros(size(opticsGet(optics, 'wave'))) + D;
[otf, sf_cycles_per_mm] = opticsDefocusCore(optics, sf_cycles_per_deg, defocus);

optics = opticsBuild2Dotf(optics, otf, sf_cycles_per_mm);
optical_image = oiSet(optical_image, 'optics', optics);
optical_image = oiCompute(optical_image, scene);
```

**Comment by wandell** [comment]
I would like this form of the calculation to be checked and clear.  I am quite busy until Monday.  But next week I will try to enlist Thomas Goossens to work through the calculations and code to check and clarify.

In the meantime there are some defocus scripts that might help you.

Brian

@Thomas ***@***.***>

Brian Wandell
Stein Family Chair
Stanford University
Http://www.stanford.edu/~wandell
________________________________

**Comment by tgoossens** [comment]
Dear @AaronWebster ,

There are two minor changes required for your snippet to work.

**1. Set the optics model to 'shift invariant'**
optics = oiGet(oi,'optics');
optics = opticsSet(optics,'model','shift invariant');

By default it will be 'diffraction limited' and will not use any OTF you give it. Instead it will use the OTF for a certain fnumber (in focus). That's why your image always remained infocus no matter what the subject distance was.

**2. Set the focal length of the optics object**
optics=opticsSet(optics,'focallength',focal_length_meters);
Without setting this, this causes a mismatch between your thin lens calculation and the iset calcualtion.

Let me know if you have additional issues.
Thomas

**Comment by AaronWebster** [comment]
That does it, thank you! Please mark as resolved.
