### ISSUE TITLE
Code issue: why does isetcam rotate psf by 180 degree before apply convolution?

### ISSUE THREAD

**Issue by greatwallet** [ISET/isetcam#30]
Hello, thank you for your inspiring work!

I am using `isetcam` to perform optical imaging using PSF generated by Zemax. However, when I was following the tutorial of [t_oiRTCompute.m](https://stanford.edu/~wandell/data/isetcam/oi/t_oiRTCompute.html), I found that every PSF generated by Zemax was rotated by 180 in [rtPrecomputePSF.m](https://github.com/ISET/isetcam/blob/7146c0d123975dbf0415efca1769c566d6d6c6fa/opticalimage/raytrace/rtPrecomputePSF.m), before applying convolution in [rtPrecomputePSFApply.m](https://github.com/ISET/isetcam/blob/7146c0d123975dbf0415efca1769c566d6d6c6fa/opticalimage/raytrace/rtPrecomputePSFApply.m), which was really confusing. 

https://github.com/ISET/isetcam/blob/7146c0d123975dbf0415efca1769c566d6d6c6fa/opticalimage/raytrace/rtPrecomputePSF.m#L148

Could you please explain why you made the rotation?

**Comment by wandell** [comment]
Thank you for your positive comment.  I am glad you find ISETCam useful.

I don’t have an answer for you.  Probably when we wrote the routine we believed there was a difference between the coordinate frame in the Zemax representation and the ISETCam representation, with the row numbering starting at the top and counting down, or starting at the bottom and counting up.  Or some coordinate issue like that.

There were many other coordinate issues and calculation bugs that came up at the time.  We did not have a copy of Zemax here at the time, and we were helped by friends who were using the code in their startup.  I suspect they felt the rotation was needed for their lens and Zemax application.

If you are using Zemax and have a case where the rotation is mistaken, or you think it should become an option, let me know.  I can make an adjustment.


--------------------
Sent from my iPad
________________________________
From: 程笑天 (Cheng Xiaotian) ***@***.***>
Sent: Sunday, October 22, 2023 7:28:41 AM
To: ISET/isetcam ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ISET/isetcam] Code issue: why does isetcam rotate psf by 180 degree before apply convolution? (Issue #30)


Hello, thank you for your inspiring work!

I am using isetcam to perform optical imaging using PSF generated by Zemax. However, when I was following the tutorial of t_oiRTCompute.m<https://stanford.edu/~wandell/data/isetcam/oi/t_oiRTCompute.html>, I found that every PSF generated by Zemax was rotated by 180 in rtPrecomputePSF.m<https://github.com/ISET/isetcam/blob/7146c0d123975dbf0415efca1769c566d6d6c6fa/opticalimage/raytrace/rtPrecomputePSF.m>, before applying convolution in rtPrecomputePSFApply.m<https://github.com/ISET/isetcam/blob/7146c0d123975dbf0415efca1769c566d6d6c6fa/opticalimage/raytrace/rtPrecomputePSFApply.m>, which was really confusing.

https://github.com/ISET/isetcam/blob/7146c0d123975dbf0415efca1769c566d6d6c6fa/opticalimage/raytrace/rtPrecomputePSF.m#L148

Could you please explain why you made the rotation?

**Comment by greatwallet** [comment]
Hello, thank you for your quick reply!

After reading the full code and giving second thoughts, I don't think the implementation is bugged. Despite that, I don't think it is relevant to coordinate issues in zemax, but a matter of implementation of convolution. 

The following is my rethinking of your code on PSF convolution. Please point out if anything is erroneous in the statement. 

The first thing I do is to sort the convolution process with spatial-varying PSF. For brevity, we assume the simplest case, where image $I$ is 3x3 in resolution, and PSF $P$ size is also 3x3.

<img width="1280" alt="屏幕截图 2023-10-23 113155" src="https://github.com/ISET/isetcam/assets/30019142/6e9cbf0a-7532-47ce-9bde-e7a6af7c9777">

Since we have spatial-varying PSF, each location in $I(x,y)$ has a corresponding PSF $P_{(x,y)}(j,i)$.

<br /> <br /><br />

For the degenerated case, all PSFs are roughly close in the neighborhood and can be expressed by a constant PSF $\bar{P}(j,i)$. And the convolution can be performed in a simple equation 
$$I_{conv}(x,y)=\sum_{i=-1}^{1}\sum_{j=-1}^1 I(x+j,y+i)\bar{P}(j,i)$$

<img width="1280" alt="屏幕截图 2023-10-23 113222" src="https://github.com/ISET/isetcam/assets/30019142/fdfb390d-094c-4e3f-bf58-33a9f42cd7ba">

 <br /> <br /><br />

Now we consider the spatial-varying case. I have read your code in [rtPrecomputePSFApply.m](https://github.com/ISET/isetcam/blob/7146c0d123975dbf0415efca1769c566d6d6c6fa/opticalimage/raytrace/rtPrecomputePSFApply.m), and I am pretty sure that `iset` replaced $\bar{P}(j,i)$ with corresponding PSF $P_{(x,y)}(j,i)$, and the convolution becomes
$$I_{conv}(x,y)=\sum_{i=-1}^{1}\sum_{j=-1}^1 I(x+j,y+i)P_{(x+j,y+i)}(j,i)$$
<img width="1280" alt="屏幕截图 2023-10-23 113309" src="https://github.com/ISET/isetcam/assets/30019142/e53f18a9-0c0e-4f5e-a10c-81a103c64b1b">

This is implemented in [rtPrecomputePSFApply.m](https://github.com/ISET/isetcam/blob/7146c0d123975dbf0415efca1769c566d6d6c6fa/opticalimage/raytrace/rtPrecomputePSFApply.m), where the summation within an area is not performed at once, but progressively in a for-loop.
https://github.com/ISET/isetcam/blob/7146c0d123975dbf0415efca1769c566d6d6c6fa/opticalimage/raytrace/rtPrecomputePSFApply.m#L293-L318

 <br /> <br /><br />
Now here comes the core issue: **why does iset rotate the PSF by 180deg  before convolution?** Here is my understanding, it is for efficient coding of batch convolution. If PSFs are not rotated beforehand, the implementation of convolution would be inconvenient.

We consider a larger image with PSF size is still 3x3. First, we consider the effect of $P_{(1,-1)}(1,-1)$ (the lower-right element enclosed by a red circle in the figure below) on $I_{conv}(0,0)$. Like what is stated above, the convolution is performed as $I_{conv}(0,0)=I(1,-1)P_{(1,-1)}(1,-1) + ... + I(0,0)P_{(0,0)}(0,0) + ...$   As in the figure below, the summation area is enclosed by the blue box.

<img width="1280" alt="屏幕截图 2023-10-23 113346" src="https://github.com/ISET/isetcam/assets/30019142/9bed3d2b-615c-4607-8588-4125893224bc">

So how do other kernel elements in $P_{(1,-1)}(j,i), (j,i)\in ([-1, 1]\times[-1,1]) \/ {(1,-1)}$ participate in the convolution? We take $P_{(1,-1)}(-1,1)$ (the upper-left corner) as an example, we summation area is shifted towards its lower-right area, just as in the following figure. And the target pixel resulting from the summation becomes $I_{conv}(2,-2)$.

<img width="1280" alt="屏幕截图 2023-10-23 113400" src="https://github.com/ISET/isetcam/assets/30019142/9ae89fe2-c463-4242-88e7-518c7c67630b">

Now we can see that: **the location of PSF kernel element and its corresponding target pixel in the image is both upside-down and flipped left to right**. $P_{(1,-1)}(1,-1)$ on the lower-right corner of $P_{(1,-1)}$ has an contribution to $(1,-1)$'s upper-left neighbor $I(0,0)$, whereas $P_{(1,-1)}(-1,1)$ on the upper-left corner of $P_{(1,-1)}$ has an contribution to $(1,-1)$'s lower-right neighbor $I(2,-2)$. In this way, rotating PSFs by 180 deg makes convolution logic easier and is convenient for batch conv implementation.

The above is my thoughts about `iset`'s way of implementation, which I think is not bugged. Please point out if any statements above are wrong. 

FYI, I am not very familiar with Zemax PSF coordination. So if there is indeed an issue in that, then there must be some error in my above statements.

**Comment by wandell** [comment]
These are very good points.  The way to formulate the pointspread for the convolution is another consideration.

I will try to read through your notes before too long.  I have a complicated 10 days coming up.  But your notes seem very clear, and I look forward to understanding them!

From: 程笑天 (Cheng Xiaotian) ***@***.***>
Date: Sunday, October 22, 2023 at 9:42 PM
To: ISET/isetcam ***@***.***>
Cc: Brian A Wandell ***@***.***>, Comment ***@***.***>
Subject: Re: [ISET/isetcam] Code issue: why does isetcam rotate psf by 180 degree before apply convolution? (Issue #30)

Hello, thank you for your quick reply!

After reading the full code and giving second thoughts, I don't think the implementation is bugged. Despite that, I don't think it is relevant to coordinate issues in zemax, but a matter of implementation of convolution.

The following is my rethinking of your code on PSF convolution. Please point out if anything is erroneous in the statement.

The first thing I do is to sort the convolution process with spatial-varying PSF. For brevity, we assume the simplest case, where image $I$ is 3x3 in resolution, and PSF $P$ size is also 3x3.
[屏幕截图 2023-10-23 113155]<https://user-images.githubusercontent.com/30019142/277223945-6e9cbf0a-7532-47ce-9bde-e7a6af7c9777.png>

Since we have spatial-varying PSF, each location in $I(x,y)$ has a corresponding PSF $P_{(x,y)}(j,i)$.



For the degenerated case, all PSFs are roughly close in the neighborhood and can be expressed by a constant PSF $\bar{P}(j,i)$. And the convolution can be performed in a simple equation
$$I_{conv}(x,y)=\sum_{i=-1}^{1}\sum_{j=-1}^1 I(x+j,y+i)\bar{P}(j,i)$$
[屏幕截图 2023-10-23 113222]<https://user-images.githubusercontent.com/30019142/277225165-fdfb390d-094c-4e3f-bf58-33a9f42cd7ba.png>



Now we consider the spatial-varying case. I have read your code in rtPrecomputePSFApply.m<https://github.com/ISET/isetcam/blob/7146c0d123975dbf0415efca1769c566d6d6c6fa/opticalimage/raytrace/rtPrecomputePSFApply.m>, and I am pretty sure that iset replaced $\bar{P}(j,i)$ with corresponding PSF $P_{(x,y)}(j,i)$, and the convolution becomes
$$I_{conv}(x,y)=\sum_{i=-1}^{1}\sum_{j=-1}^1 I(x+j,y+i)P_{(x+j,y+i)}(j,i)$$
[屏幕截图 2023-10-23 113309]

This is implemented in rtPrecomputePSFApply.m<https://github.com/ISET/isetcam/blob/7146c0d123975dbf0415efca1769c566d6d6c6fa/opticalimage/raytrace/rtPrecomputePSFApply.m>, where the summation within an area is not performed at once, but progressively in a for-loop.
https://github.com/ISET/isetcam/blob/7146c0d123975dbf0415efca1769c566d6d6c6fa/opticalimage/raytrace/rtPrecomputePSFApply.m#L293-L318




Now here comes the core issue: why does iset rotate the PSF by 180deg before convolution? Here is my understanding, it is for efficient coding of batch convolution. If PSFs are not rotated beforehand, the implementation of convolution would be inconvenient.

We consider a larger image with PSF size is still 3x3. First, we consider the effect of $P_{(1,-1)}(1,-1)$ (the lower-right element enclosed by a red circle in the figure below) on $I_{conv}(0,0)$. Like what is stated above, the convolution is performed as $I_{conv}(0,0)=I(1,-1)P_{(1,-1)}(1,-1) + ... + I(0,0)P_{(0,0)}(0,0) + ...$ As in the figure below, the summation area is enclosed by the blue box.
[屏幕截图 2023-10-23 113346]<https://user-images.githubusercontent.com/30019142/277228349-9bed3d2b-615c-4607-8588-4125893224bc.png>

So how do other kernel elements in $P_{(1,-1)}(j,i), (j,i)\in ([-1, 1]\times[-1,1]) / {(1,-1)}$ participate in the convolution? We take $P_{(1,-1)}(-1,1)$ (the upper-left corner) as an example, we summation area is shifted towards its lower-right area, just as in the following figure. And the target pixel resulting from the summation becomes $I_{conv}(2,-2)$.
[屏幕截图 2023-10-23 113400]<https://user-images.githubusercontent.com/30019142/277229221-9ae89fe2-c463-4242-88e7-518c7c67630b.png>

Now we can see that: the location of PSF kernel element and its corresponding target pixel in the image is both upside-down and flipped left to right. $P_{(1,-1)}(1,-1)$ on the lower-right corner of $P_{(1,-1)}$ has an contribution to $(1,-1)$'s upper-left neighbor $I(0,0)$, whereas $P_{(1,-1)}(-1,1)$ on the upper-left corner of $P_{(1,-1)}$ has an contribution to $(1,-1)$'s lower-right neighbor $I(2,-2)$. In this way, rotating PSFs by 180 deg makes convolution logic easier and is convenient for batch conv implementation.

The above is my thoughts about iset's way of implementation, which I think is not bugged. Please point out if any statements above are wrong.

FYI, I am not very familiar with Zemax PSF coordination. So if there is indeed an issue in that, then there must be some error in my above statements.

**Comment by greatwallet** [comment]
Hi, thank you for your reply.

I think I have made things too complicated. The reason for PSF rotation is that 2D convolution needs the kernel to be flipped. And this should be all.

**Comment by wandell** [comment]
Great to see you checking and thinking out loud!  I should have helped you.  Glad for grout clear answer.

Brian Wandell
Stein Family Chair
Stanford University
Http://www.stanford.edu/~wandell
________________________________
