### ISSUE TITLE
Unrecognized function or variable 'hObject'.

### ISSUE THREAD

**Issue by FengJin2023** [ISET/isetcam#31]
I got too many errors while loading and changing parameters in the scene and sensor.
How to solve it?

Unrecognized function or variable 'hObject'.

Error in sensorWindow_App/menuEditCreate_Callback (line 1166)
            createNewSensor(app, hObject, eventdata, handles);

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
            newCallback = @(source, event)executeCallback(ams, ...

**Comment by wandell** [comment]
What were you doing?  I can have a look if you tell me how to create the error.

--------------------
Sent from my iPad
________________________________
From: FengJin2023 ***@***.***>
Sent: Thursday, November 16, 2023 7:46:09 AM
To: ISET/isetcam ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ISET/isetcam] Unrecognized function or variable 'hObject'. (Issue #31)


I got too many errors while loading and changing parameters in the scene and sensor.
How to solve it?

Unrecognized function or variable 'hObject'.

Error in sensorWindow_App/menuEditCreate_Callback (line 1166)
createNewSensor(app, hObject, eventdata, handles);

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
newCallback = @(source, event)executeCallback(ams, ...

**Comment by FengJin2023** [comment]
Thank you for your reply.

I was trying to adjust luminance and Distance in scene.
<img width="573" alt="hObject_error" src="https://github.com/ISET/isetcam/assets/138052631/af96cef9-a3f2-4c6d-8125-c8dcfe6e2774">

**Comment by wandell** [comment]
I can replicate the bug. I think I fixed it.  Give it a try after doing a ‘git pull’ from either ‘dev’ or ‘master’.



From: FengJin2023 ***@***.***>
Date: Thursday, November 16, 2023 at 8:03 AM
To: ISET/isetcam ***@***.***>
Cc: Brian A Wandell ***@***.***>, Comment ***@***.***>
Subject: Re: [ISET/isetcam] Unrecognized function or variable 'hObject'. (Issue #31)

Thank you for your reply.

I was trying to adjust luminance and Distance in scene.
[hObject_error]<https://user-images.githubusercontent.com/138052631/283516455-af96cef9-a3f2-4c6d-8125-c8dcfe6e2774.png>

**Comment by FengJin2023** [comment]
Thank you so much for your quick release.
I can use luminance now.

However, I got another same error adjust distance.
<img width="1211" alt="Distance_hObject_error" src="https://github.com/ISET/isetcam/assets/138052631/896890b7-6ced-4e65-ba58-a91bf9cd1a15">





FYI, since I am totally new to ISETcam and Matlab, I will have many questions regarding your tool.

**Comment by FengJin2023** [comment]
> Thank you so much for your quick release. I can use luminance now.
> 
> However, I got another same error adjust distance. <img alt="Distance_hObject_error" width="1211" src="https://user-images.githubusercontent.com/138052631/283536992-896890b7-6ced-4e65-ba58-a91bf9cd1a15.png">
> 
> FYI, since I am totally new to ISETcam and Matlab, I will have many questions regarding your tool.
I am using MATLAB R2023b Update 3. And I am also facing other same errors optics and sensors.
Could MATLAB be the problem?

**Comment by wandell** [comment]
Notice that the error on the left and the code on the right are not the same.  In fact, that is the line that I replaced this morning.  So this suggests that you didn’t restart the window and use the new code.

Try closing the app and starting again.

(I have to go teach for a couple of hours.  I won’t be able to respond until this evening).

Brian

From: FengJin2023 ***@***.***>
Date: Thursday, November 16, 2023 at 9:15 AM
To: ISET/isetcam ***@***.***>
Cc: Brian A Wandell ***@***.***>, Comment ***@***.***>
Subject: Re: [ISET/isetcam] Unrecognized function or variable 'hObject'. (Issue #31)

Thank you so much for your quick release. I can use luminance now.

However, I got another same error adjust distance. [Distance_hObject_error] <https://user-images.githubusercontent.com/138052631/283536992-896890b7-6ced-4e65-ba58-a91bf9cd1a15.png>

FYI, since I am totally new to ISETcam and Matlab, I will have many questions regarding your tool.
I am using MATLAB R2023b Update 3. And I am also facing other same errors optics and sensors.
Could MATLAB be the problem?
