### ISSUE TITLE
Why shift image in spatial domain before applying OTF?

### ISSUE THREAD

**Issue by kfeng19** [ISET/isetcam#6]
In oiApplyOTF, the image is fftshifted before fft2. Then it is shifted back after ifft2. I am curious about the purpose of these spatial domain shifts.
 
``` MATLAB
    % For diffraction limited we calculate the OTF.  For other optics
    % models we look up the stored OTF.  Remember, DC is in the (1,1)
    % position.
    otf = oiCalculateOTF(oi,wave(ii),unit);
    % figure(1); mesh(otf); otf(1,1)
    
    % Put the image center in (1,1) and take the transform.
    imgFFT = fft2(fftshift(img));
    % figure(1); imagesc(abs(imgFFT));  
    % figure(2); imagesc(abs(otf));
    % colormap(gray)
    
    % Multiply the transformed otf and the image.  
    % Then invert and put the image center in  the center of the matrix 
    filteredIMG = abs(ifftshift(ifft2(otf .* imgFFT)));
```

**Comment by wandell** [comment]
You are right!  These were left over and are should not be there.  I removed them, tested the new code, and the validation script passed just fine.  

I will continue testing for any small differences.  If everything goes well through the end of today (I am doing some calculations), I will push the change. You saved us some compute time!

I made one other small change, too, that will speed up the code in oiApplyOTF.  We now precompute the OTF for all wavelengths rather than make the compute call multiple times.
